# Site settings
title: Mark's Portfolio
description: Mark Kuczmarski is a software developer from Cleveland Ohio.  
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mark Kuczmarski
user_description: I am a software developer from Cleveland, Ohio.  I lived in the San Franciso Bay Area for a few years and now I am living in Tokyo Japan.  I love learning new things and helping others acheive their goals. 
user_title: Software Developer
email: markkuczmarski@gmail.com
github_username:  kuczmama

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
